{{ if eq .Values.diffgramEdition "enterprise"}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullCredentials.gcrCredentials }}
kind: Secret

metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade, pre-rollback
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl
    operation: Update
  name: db-migrations-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{ end }}