{{ if eq .Values.diffgramEdition "enterprise"}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullCredentials.gcrCredentials }}
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl
    operation: Update
  name: diffgramsecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{ end }}