{{ if eq .Values.dbSettings.dbProvider "local"}}
apiVersion: v1
kind: Service
metadata:
  name: diffgram-postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
{{ end }}